# Generated by Django 4.1 on 2022-08-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0011_alter_invoiceitem_tax_rates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField()),
                ('price', models.ForeignKey(help_text="The user's Stripe price object, if it exists", on_delete=django.db.models.deletion.CASCADE, to='djstripe.price')),
            ],
        ),
    ]
